export const CATEGORY_PANADERIA = "PANADERIA";
export const CATEGORY_PASTELERIA = "PASTELERIA";
export const CATEGORY_VEGETARIANO = "VEGETARIANO";
export const CATEGORY_VEGANO = "VEGANO";
export const CATEGORY_ARTESANIAS = "ARTESANIAS";
export const CATEGORY_CARRITO = "CARRITO";
export const CATEGORY_USER = "USUARIO";
export const ORDER_CONFIRMATION = "CONFIRMACION DE PEDIDO";
export const ADMIN = "ADMIN";
export const UPDATE_BUTTON_TEXT = "EDITAR INFORMACION";
export const SAVE_BUTTON_TEXT = "GUARDAR INFORMACION";
export const CONFIRM_ORDER_BUTTON_TEXT = "CONFIRMAR PEDIDO";
export const VARIANT_STANDARD = "standard";
export const VARIANT_OUTLINED = "outlined";
export const LOGIN_TITLE_TEXT = "INICIAR SESION";
export const LOGOUT_TITLE = "CERRAR SESSION ";
export const USER_DATA_TITLE = "DATOS DEL USUARIO";
export const ADMIN_BUTTON_TEXT = "ADMINISTRAR";
export const EMPTY_CART_MESSAGE = "TU CARRITO ESTA VACIO";
export const ADD_TO_CART_BUTTON_TEXT = "AGREGAR AL CARRITO";
export const FACEBOOK = "Facebook";
export const INSTAGRAM = "Instagram";
export const WHATSAPP = "WhatsApp";


