export const CATEGORY_PANADERIA = "PANADERIA";
export const CATEGORY_PASTELERIA = "PASTELERIA";
export const CATEGORY_VEGETARIANO = "VEGETARIANO";
export const CATEGORY_VEGANO = "VEGANO";
export const CATEGORY_ARTESANIAS = "ARTESANIAS";
export const CATEGORY_CARRITO = "CARRITO";
export const CATEGORY_USER = "USUARIO";
export const ORDER_CONFIRMATION = "CONFIRMACION DE PEDIDO"
